### ISSUE TITLE
irb_kernel cannot start

### ISSUE THREAD

**Issue by kojix2** [PyDataOsaka/irb_kernel#1]
Error message

```
Traceback (most recent call last):
  File "/home/kojix2/anaconda3/bin/jupyter-console", line 6, in <module>
    from jupyter_console.app import main
  File "/home/kojix2/anaconda3/lib/python3.7/site-packages/jupyter_console/app.py", line 26, in <module>
    from jupyter_console.ptshell import ZMQTerminalInteractiveShell
  File "/home/kojix2/anaconda3/lib/python3.7/site-packages/jupyter_console/ptshell.py", line 22, in <module>
    from IPython.utils.py3compat import cast_unicode_py2, input
ImportError: cannot import name 'cast_unicode_py2' from 'IPython.utils.py3compat' (/home/kojix2/anaconda3/lib/python3.7/site-packages/IPython/utils/py3compat.py)
```

**Comment by kojix2** [comment]
Qt console
```
Traceback (most recent call last):
  File "/home/kojix2/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/kojix2/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/kojix2/anaconda3/lib/python3.7/site-packages/irb_kernel/__main__.py", line 3, in <module>
    IPKernelApp.launch_instance(kernel_class=IrbKernel)
  File "/home/kojix2/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "</home/kojix2/anaconda3/lib/python3.7/site-packages/decorator.py:decorator-gen-124>", line 2, in initialize
  File "/home/kojix2/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/kojix2/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 562, in initialize
    self.init_kernel()
  File "/home/kojix2/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 447, in init_kernel
    user_ns=self.user_ns,
  File "/home/kojix2/anaconda3/lib/python3.7/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/home/kojix2/anaconda3/lib/python3.7/site-packages/irb_kernel/kernel.py", line 24, in __init__
    self._start_irb()
  File "/home/kojix2/anaconda3/lib/python3.7/site-packages/irb_kernel/kernel.py", line 29, in _start_irb
    self.irbwrapper = replwrap.REPLWrapper("irb --simple-prompt", ">> ", None)
  File "/home/kojix2/anaconda3/lib/python3.7/site-packages/pexpect/replwrap.py", line 55, in __init__
    self._expect_prompt()
  File "/home/kojix2/anaconda3/lib/python3.7/site-packages/pexpect/replwrap.py", line 66, in _expect_prompt
    timeout=timeout, async_=async_)
  File "/home/kojix2/anaconda3/lib/python3.7/site-packages/pexpect/spawnbase.py", line 421, in expect_exact
    return exp.expect_loop(timeout)
  File "/home/kojix2/anaconda3/lib/python3.7/site-packages/pexpect/expect.py", line 181, in expect_loop
    return self.timeout(e)
  File "/home/kojix2/anaconda3/lib/python3.7/site-packages/pexpect/expect.py", line 144, in timeout
    raise exc
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x7fcf475d7990>
command: /home/kojix2/.rbenv/shims/irb
args: [b'/home/kojix2/.rbenv/shims/irb', b'--simple-prompt']
buffer (last 100 chars): '\x1b[1G▽\x1b[6n'
before (last 100 chars): '\x1b[1G▽\x1b[6n'
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 9445
child_fd: 37
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: '>> '
    1: '[PEXPECT_PROMPT+'
[JupyterQtConsoleApp] KernelRestarter: restarting kernel (1/5), keep random ports
[JupyterQtConsoleApp] WARNING | kernel restarted
```

**Comment by kozo2** [comment]
Sorry, I don't have the plan to add `rbenv` support.
Please try the following commands instead.
```
/home/kojix2/anaconda3/bin/conda install pip jupyter pexpect notebook jupyter_console
/home/kojix2/anaconda3/bin/conda update conda python pip jupyter pexpect notebook jupyter_console
/home/kojix2/anaconda3/bin/conda install -c conda-forge ruby
/home/kojix2/anaconda3/bin/conda clean -a
/home/kojix2/anaconda3/bin/pip install irb_kernel -U
/home/kojix2/anaconda3/bin/python -m irb_kernel.install
/home/kojix2/anaconda3/bin/conda init
```
Then **restart your shell** and run
```
/home/kojix2/anaconda3/bin/jupyter-console --kernel irb
# or
/home/kojix2/anaconda3/bin/jupyter-notebook
```

**Comment by kozo2** [comment]
First, try to use irb which is installed by `ruby` debian package instead of rbenv.

**Comment by kozo2** [comment]
If you want to use rbenv, please check this first.
```
/home/kojix2/anaconda3/bin/python
```
Then run the following line by line in the python REPL
```
from pexpect import replwrap
rb=replwrap.REPLWrapper("rbenvのirbのフルパス --simple-prompt", ">> ", None)
rb.run_command("1+2")
```
And check you can get 3

**Comment by kozo2** [comment]
Sorry, I removed the mension about Qt console.
There are no plan to support Qt console in the future.

**Comment by kojix2** [comment]
This seems to be caused by a newer version of irb.
I confirmed that the old irb works correctly.
